language: python
python:
  - "2.7"
  - "2.6"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - pip install coveralls
  - pip install .
script: 
  - python csv_io.py
  - python -m hnapi.connectors.api_connector
  - python -m hnapi.items.storyitem
  - python -m hnapi.items.useritem
  - python -m hnapi.items.updatesitem
  - python -m hnapi.items.commentitem
  - python -m hnapi.schemas.storyschema
  - python -m hnapi.schemas.userschema
  - python -m hnapi.schemas.updatesschema
  - python -m hnapi.schemas.commentschema
  - nosetests --with-coverage --cover-package=hnapi
after_success:
  coveralls
