language: python
python:
  - "2.7"
  - "2.6"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
install:
  - pip install coveralls
  - pip install .
script: 
  - python -m hnapi.hnapi
  - python -m hnapi.hnitem
  - nosetests --with-coverage --cover-package=hnapi
after_success:
  coveralls
